apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpid-server
  namespace: default
  labels:
    app: mpid-server
spec:
  selector:
    matchLabels:
      app: mpid-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mpid-server
    spec:
      containers:
      - name: mpid-server
        image:  lailemon/mpid-server:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --config
        - /mpid-server/config.yml
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  8000
          name: http
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: config
          mountPath: /mpid-server
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: config
          configMap:
            name: mpid-server
      restartPolicy: Always