apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yml
- svc.yml


images:
- name: lailemon/mpid-server
  newTag: v0.0.1


configMapGenerator:
- files:
  - config.yml
  name: mpid-server
  
labels:
- includeSelectors: true
  pairs:
    app: mpid-server
