---
# Redis Service（Headless Service，用于StatefulSet的网络标识）
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
  type: LoadBalancer
